test:
  version: V2.0
spring:
  cloud:
    config:
      retry:
        max-attempts: 6 # 配置重试次数，默认为6
        multiplier: 1.1 # 间隔乘数，默认1.1
        initial-interval: 1000 # 初始重试间隔时间，默认1000ms
        max-interval: 2000 # 最大间隔时间，默认2000ms